name: TPM Tests
on: [push]
jobs:
  tpm-tests:
    name: TPM E2E Tests
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: local
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install swtpm
      run: |
        sudo apt-get update
        sudo apt-get install -y swtpm

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Test tpmsecrets
      working-directory: ./tpmsecrets
      run: go test -v ./...
