name: TPM Tests Windows
on: [push]
jobs:
  tpm-tests-windows:
    name: TPM E2E Tests (Windows)
    runs-on: windows-latest
    env:
      GOTOOLCHAIN: local
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    # TODO - this at least makes sure it compiles, but the actions runner
    # doesn't have a TPM. Would be nice to have one that does.
    - name: Test tpmsecrets
      working-directory: ./tpmsecrets
      run: go test -v ./...
